# Hashicorp Vault
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the precise32 base box installed...
# vagrant box add precise32 http://files.vagrantup.com/precise32.box

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "vault.centos.box"
  config.vm.network :private_network, ip: "192.168.0.43"
  config.vm.network "forwarded_port", guest: 8200, host: 8200

  config.vm.provider :virtualbox do |vb|
    vb.memory = 256
  end
  config.vm.provision "shell" do |s|
    s.path = "install-vault.sh"
  end
end
