# Chef Nodes Fetching Secrets From Hashicorp Vault
#
# NOTE: Make sure you have the centos/7 base box installed...
# vagrant box add centos/7

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    chef.vm.box = "centos/7"
    chef.vm.hostname = "node1.centos.box"
    chef.vm.network :private_network, ip: "192.168.0.44"
    chef.vm.provider :virtualbox do |vb|
      vb.memory = 256
    end
    chef.vm.provision "shell" do |s|
      s.path = "install-node.sh"
    end
  end
end
