# Chef Server
#
# Single box with VirtualBox provider and Puppet provisioning.
#
# NOTE: Make sure you have the precise32 base box installed...
# vagrant box add precise32 http://files.vagrantup.com/precise32.box

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "chef.centos.box"
  config.vm.network :private_network, ip: "192.168.0.42"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 4000
    vb.cpus = 4
  end
  config.vm.provision "shell" do |s|
    s.args = [config.vm.hostname, 'ADMIN@EMAIL.HERE']
    s.path = "install-chef.sh"
  end
end
