# Chef Nodes Fetching Secrets From Hashicorp Vault
#
# NOTE: Make sure you have the centos/7 base box installed...
# vagrant box add centos/7

Vagrant.configure("2") do |config|
  config.vm.define "chef-server" do |chef|
    chef.vm.box = "centos/7"
    chef.vm.hostname = "chef.centos.box"
    chef.vm.network :private_network, ip: "192.168.0.43"
    chef.vm.provider :virtualbox do |vb|
      vb.memory = 4000
      vb.cpus = 4
    end
    chef.vm.provision "shell" do |s|
      s.args = [config.vm.hostname, 'ADMIN@EMAIL.HERE']
      s.path = "ChefServer/install-chef.sh"
    end
  end
  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.hostname = "node1.centos.box"
    node1.vm.network :private_network, ip: "192.168.0.44"
    node1.vm.provider :virtualbox do |vb|
      vb.memory = 256
    end
    node1.vm.provision "shell" do |s|
      s.path = "install-node.sh"
    end
  end
  config.vm.define "workstation" do |wk|
    wk.vm.box = "centos/7"
    wk.vm.hostname = "wk2.centos.box"
    wk.vm.network :private_network, ip: "192.168.0.45"
    wk.vm.provider :virtualbox do |vb|
      vb.memory = 256
    end
    wk.vm.provision "shell" do |s|
      s.path = "ChefWorkstation/install-wk.sh"
    end
  end
end
